name: Repository Dispatch

on:
  repository_dispatch:
    types: [new-image]

jobs:
  update-values:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Update Image Tag in Helm Values
        uses: mikefarah/yq@master
        with:
          # Cắt chuỗi lấy phần sau dấu hai chấm (ví dụ: "12") gán vào tag
          cmd: yq eval '.image.tag = sub("${{ github.event.client_payload.image }}", ".*:", "")' -i spring-boot-chart/values.yaml
        
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "feat(helm): update image tag via dispatch to ${{ github.event.client_payload.image }}"
